import random
ls=[]
ls.append(1)
print(ls)
ls.append(2)
ls.append(3)
ls.append(3)
ls.append(3)
ls1=[x for x in range(1,9)]
print(ls1)
l=random.random()
print(random.getrandbits(10))
print(random.getstate())
print(l)
ls1.pop()
print(ls1)
print(9 in ls1)
print(random.uniform(1,10))
del ls1[4]
print(ls1)
random.seed(19)
print(random.uniform(9,20))
print(random.triangular(10,20,9))
ls2=list(ls1[-1:])
print(ls2)
print(ls1)
#print(len(ls1))
for i in range(len(ls1)-1,0,-1):
    print(ls1[i])
print(ls1[0])
print(ls.reverse())
print(ls1[::-1])
print(ls.remove(3))
print(ls)
print(ls1)
print(random.choice(ls1))